[package]
name = "utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webbrowser = "0.8.10"
interface = { path="../interface" }
async-trait = "0.1.72"
bytes = "1.4.0"
